// Generated by gencpp from file conqu/ByteArray.msg
// DO NOT EDIT!


#ifndef CONQU_MESSAGE_BYTEARRAY_H
#define CONQU_MESSAGE_BYTEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conqu
{
template <class ContainerAllocator>
struct ByteArray_
{
  typedef ByteArray_<ContainerAllocator> Type;

  ByteArray_()
    : data()  {
      data.assign(0);
  }
  ByteArray_(const ContainerAllocator& _alloc)
    : data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef boost::array<int8_t, 10>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::conqu::ByteArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conqu::ByteArray_<ContainerAllocator> const> ConstPtr;

}; // struct ByteArray_

typedef ::conqu::ByteArray_<std::allocator<void> > ByteArray;

typedef boost::shared_ptr< ::conqu::ByteArray > ByteArrayPtr;
typedef boost::shared_ptr< ::conqu::ByteArray const> ByteArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conqu::ByteArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conqu::ByteArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conqu::ByteArray_<ContainerAllocator1> & lhs, const ::conqu::ByteArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conqu::ByteArray_<ContainerAllocator1> & lhs, const ::conqu::ByteArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conqu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conqu::ByteArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conqu::ByteArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conqu::ByteArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conqu::ByteArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conqu::ByteArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conqu::ByteArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conqu::ByteArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56792dc2ab08b5a97efe471984a66192";
  }

  static const char* value(const ::conqu::ByteArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56792dc2ab08b5a9ULL;
  static const uint64_t static_value2 = 0x7efe471984a66192ULL;
};

template<class ContainerAllocator>
struct DataType< ::conqu::ByteArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conqu/ByteArray";
  }

  static const char* value(const ::conqu::ByteArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conqu::ByteArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[10] data\n"
;
  }

  static const char* value(const ::conqu::ByteArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conqu::ByteArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ByteArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conqu::ByteArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conqu::ByteArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONQU_MESSAGE_BYTEARRAY_H
